import { Artwork, Service, Category } from '@/types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'photography', label: 'تصوير', color: '#3B82F6', description: 'التصوير الفوتوغرافي الفني والتوثيقي', sortOrder: 1 },
  { id: 'painting', label: 'فن تشكيلي', color: '#10B981', description: 'اللوحات الزيتية والأكريليكية', sortOrder: 2 },
  { id: 'calligraphy', label: 'خط عربي', color: '#8B5CF6', description: 'الخط العربي الكلاسيكي والمعاصر', sortOrder: 3 },
  { id: 'design', label: 'تصميم', color: '#F59E0B', description: 'تصميم الهويات البصرية والشعارات', sortOrder: 4 },
  { id: 'portrait', label: 'بورتريه', color: '#EF4444', description: 'رسم البورتريهات الفنية', sortOrder: 5 },
];

export const ARTWORKS: Artwork[] = [
  {
    id: 'aw-001',
    title: 'لوحة زيتية — واحة غات',
    category: 'painting',
    description: 'لوحة زيتية تصور جمال واحة غات في أوقات غروب الشمس، بألوان دافئة تعكس روح الصحراء الليبية.',
    dimensions: '60×80 سم',
    technique: 'زيت على كانفاس',
    price: 850,
    images: [
      'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&q=80',
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80',
    ],
    dateAdded: '2024-01-15',
    isFeatured: true,
  },
  {
    id: 'aw-002',
    title: 'بسملة — خط الثلث',
    category: 'calligraphy',
    description: 'خط البسملة بخط الثلث الكلاسيكي على ورق مقهر بالذهب، مزخرفة بإطار هندسي مستوحى من الزخارف الأندلسية.',
    dimensions: '40×60 سم',
    technique: 'حبر وذهب على ورق مقهر',
    price: 450,
    images: [
      'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&q=80',
      'https://images.unsplash.com/photo-1614792631536-4b2531f8b8c2?w=800&q=80',
    ],
    dateAdded: '2024-02-10',
    isFeatured: true,
  },
  {
    id: 'aw-003',
    title: 'جلسة تصوير — صحراء غات',
    category: 'photography',
    description: 'صورة فنية التقطت في كثبان رمال غات مع ضوء ذهبي، تجمع بين الإنسان والطبيعة الصحراوية.',
    dimensions: '50×70 سم (مطبوع)',
    technique: 'تصوير رقمي — طباعة فاخرة',
    price: 320,
    images: [
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80',
      'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    ],
    dateAdded: '2024-03-01',
  },
  {
    id: 'aw-004',
    title: 'هوية بصرية — شركة تجارية',
    category: 'design',
    description: 'هوية بصرية كاملة لشركة تجارية ليبية، تتضمن الشعار والألوان والخطوط وتطبيقات العلامة التجارية.',
    isPriceOnRequest: true,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    ],
    dateAdded: '2024-01-28',
  },
  {
    id: 'aw-005',
    title: 'بورتريه — شيخ الصحراء',
    category: 'portrait',
    description: 'بورتريه فني بالألوان المائية لشيخ طوارقي بعمامته الزرقاء، يجسد حكمة الصحراء وأصالة أبنائها.',
    dimensions: '35×50 سم',
    technique: 'ألوان مائية على ورق فاخر',
    price: 600,
    images: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
    ],
    dateAdded: '2024-02-20',
    isFeatured: true,
  },
  {
    id: 'aw-006',
    title: 'آية الكرسي — ديواني جلي',
    category: 'calligraphy',
    description: 'آية الكرسي بخط الديواني الجلي، على لوحة منحوتة بإطار مذهب، عمل فني راقٍ للمنازل والمكاتب.',
    dimensions: '70×100 سم',
    technique: 'حبر وذهب على لوحة خشبية',
    price: 1200,
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
      'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&q=80',
    ],
    dateAdded: '2024-03-15',
    isFeatured: true,
  },
  {
    id: 'aw-007',
    title: 'مشهد صحراوي — ليلة نجوم',
    category: 'painting',
    description: 'لوحة أكريليك تصور ليلة صحراوية مرصعة بالنجوم فوق كثبان الرمال، تعكس سحر صحراء فزان.',
    dimensions: '50×70 سم',
    technique: 'أكريليك على كانفاس',
    price: 720,
    images: [
      'https://images.unsplash.com/photo-1446329813274-7c9036bd9a1f?w=800&q=80',
    ],
    dateAdded: '2024-04-01',
  },
  {
    id: 'aw-008',
    title: 'تصوير منتجات — متجر حرف',
    category: 'photography',
    description: 'جلسة تصوير احترافية للمنتجات الحرفية والتراثية، بإضاءة فنية تبرز جمال التفاصيل.',
    price: 250,
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    ],
    dateAdded: '2024-04-10',
  },
  {
    id: 'aw-009',
    title: 'شعار — مشروع سياحي',
    category: 'design',
    description: 'تصميم شعار لمشروع سياحي يجمع بين الحداثة والتراث الطوارقي، مع نظام هوية كامل.',
    isPriceOnRequest: true,
    images: [
      'https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=800&q=80',
    ],
    dateAdded: '2024-03-25',
  },
  {
    id: 'aw-010',
    title: 'بورتريه عائلي — جلسة خارجية',
    category: 'portrait',
    description: 'بورتريه عائلي بالألوان الزيتية من صورة، تصوير في فضاء طبيعي مع ألوان دافئة.',
    price: 800,
    images: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80',
    ],
    dateAdded: '2024-04-20',
  },
  {
    id: 'aw-011',
    title: 'تصوير طبيعة — فجر الصحراء',
    category: 'photography',
    description: 'لحظة الفجر فوق صحراء فزان، ألوان برتقالية وذهبية تلمس الرمال اللانهائية.',
    dimensions: '60×90 سم (مطبوع)',
    technique: 'تصوير فوتوغرافي — طباعة كانفاس',
    price: 380,
    images: [
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80',
    ],
    dateAdded: '2024-04-25',
  },
  {
    id: 'aw-012',
    title: 'لوحة مائية — خيمة رحّالة',
    category: 'painting',
    description: 'مشهد رومانسي لخيمة الطوارق وسط الصحراء بالألوان المائية الشفافة.',
    dimensions: '40×55 سم',
    technique: 'ألوان مائية',
    price: 480,
    images: [
      'https://images.unsplash.com/photo-1456086272160-b28b0645b729?w=800&q=80',
    ],
    dateAdded: '2024-05-01',
  },
];

export const SERVICES: Service[] = [
  {
    id: 'sv-001',
    title: 'جلسات التصوير',
    description: 'جلسات تصوير احترافية للأفراد، الأعراس، المنتجات بإضاءة وأجواء فنية مميزة.',
    details: [
      'جلسات فردية وعائلية',
      'تصوير الأعراس والمناسبات',
      'تصوير المنتجات والحرف',
      'جلسات في الطبيعة والاستوديو',
      'تسليم صور مُحررة عالية الجودة',
    ],
    duration: '2-4 ساعات',
    priceRange: '200-600 دينار',
    category: 'photography',
    coverImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
    requiresDeposit: true,
  },
  {
    id: 'sv-002',
    title: 'تصميم شعارات وهويات بصرية',
    description: 'تصميم شعارات احترافية وهويات بصرية كاملة لمشاريعك التجارية بأسلوب عصري.',
    details: [
      'تصميم شعار مخصص',
      'دليل الهوية البصرية',
      'تطبيقات الهوية (بطاقات، ترويسة)',
      '3 مراجعات مضمونة',
      'تسليم ملفات متعددة الصيغ',
    ],
    duration: '5-14 يوم',
    priceRange: 'حسب الطلب',
    category: 'design',
    coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    requiresDeposit: true,
  },
  {
    id: 'sv-003',
    title: 'رسم البورتريه',
    description: 'بورتريهات فنية مخصصة بالرسم اليدوي من صورتك أو من الطبيعة بتقنيات متعددة.',
    details: [
      'بورتريه فردي أو جماعي',
      'تقنيات: زيت، مائي، رصاص',
      'رسم من صورة أو جلسة مباشرة',
      'إمكانية إضافة خلفيات مخصصة',
      'تسليم مع إطار اختياري',
    ],
    duration: '7-21 يوم',
    priceRange: '300-1000 دينار',
    category: 'portrait',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80',
    requiresDeposit: true,
  },
  {
    id: 'sv-004',
    title: 'أعمال الخط العربي المخصصة',
    description: 'خط عربي مخصص بأسلوبك المفضل — آيات قرآنية، أشعار، حكم، أسماء بخطوط كلاسيكية راقية.',
    details: [
      'ثلث، نسخ، ديواني، كوفي',
      'تخطيط الآيات والأشعار',
      'أسماء وعبارات مخصصة',
      'خيارات الألوان والأبعاد',
      'قابل للتأطير والتعليق',
    ],
    duration: '3-10 أيام',
    priceRange: '150-600 دينار',
    category: 'calligraphy',
    coverImage: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&q=80',
    requiresDeposit: true,
  },
  {
    id: 'sv-005',
    title: 'التصوير الفوتوغرافي الفني',
    description: 'تصوير فني بمفهوم إبداعي — صور حرفة، تراث، طبيعة، أو مفاهيم فنية خاصة.',
    details: [
      'تصوير بمفهوم إبداعي مخصص',
      'إخراج فني كامل',
      'تحرير ومعالجة احترافية',
      'طباعة عالية الجودة اختيارية',
      'حقوق الاستخدام التجاري',
    ],
    duration: '1-3 أيام',
    priceRange: '300-800 دينار',
    category: 'photography',
    coverImage: 'https://images.unsplash.com/photo-1500051638674-ff996a0ec29e?w=800&q=80',
    requiresDeposit: true,
  },
];

export const REVIEWS = [
  {
    id: 'rv-001',
    customerName: 'فاطمة الزهراء',
    rating: 5,
    comment: 'عمل رائع جداً! أستاذ عبد العزيز فنان حقيقي، الخط جاء فوق التوقعات. الاحترافية والدقة في التنفيذ لا مثيل لهما.',
    status: 'published' as const,
    dateCreated: '2024-03-10',
  },
  {
    id: 'rv-002',
    customerName: 'محمد التاورغي',
    rating: 5,
    comment: 'جلسة تصوير ممتازة، الأستاذ محترف جداً ومريح في التعامل. الصور جاءت بجودة استثنائية وفي الوقت المحدد.',
    status: 'published' as const,
    dateCreated: '2024-02-15',
  },
  {
    id: 'rv-003',
    customerName: 'عائشة أبو بكر',
    rating: 4,
    comment: 'البورتريه جميل جداً وأسعدني كثيراً. التواصل كان سهلاً والتسليم في الموعد.',
    status: 'published' as const,
    reply: 'شكراً جزيلاً، يسعدني أن العمل نال إعجابكم.',
    dateCreated: '2024-04-05',
  },
  {
    id: 'rv-004',
    customerName: 'يوسف المبروك',
    rating: 5,
    comment: 'هوية بصرية متكاملة وإبداعية لمشروعي. الأستاذ عبد العزيز فهم رؤيتي وجسدها في تصميم احترافي.',
    status: 'published' as const,
    dateCreated: '2024-03-28',
  },
];

export const WHATSAPP_NUMBER = '218910000000';

export const FAQ_ITEMS = [
  { q: 'كم تستغرق مدة تنفيذ الخدمات المخصصة؟', a: 'تختلف المدة حسب نوع الخدمة: الخط العربي 3-10 أيام، البورتريه 7-21 يوم، التصميم 5-14 يوم، التصوير 1-3 أيام.' },
  { q: 'هل يلزم دفع عربون؟', a: 'نعم، للخدمات المخصصة يُشترط دفع عربون 20-30% من قيمة الطلب قبل بدء التنفيذ. للأعمال الجاهزة لا يلزم عربون.' },
  { q: 'ما هي طرق الدفع المتاحة؟', a: 'نقبل الدفع نقداً عند الاستلام أو التحويل البنكي (يُرسل إشعار التحويل عبر واتساب).' },
  { q: 'هل تتوفر خدمة الشحن؟', a: 'نعم، نوفر التسليم اليدوي في غات والمناطق القريبة، والشحن عبر شركات النقل للمدن الأخرى (على حساب العميل).' },
  { q: 'ما هي سياسة الإلغاء والاسترجاع؟', a: 'للأعمال الجاهزة: إلغاء كامل قبل التسليم. للخدمات المخصصة: العربون قابل للاسترجاع 50% قبل بدء التنفيذ، وغير مسترجع بعد البدء.' },
  { q: 'هل يمكنني طلب صور المنتجات قبل الشراء؟', a: 'بالطبع، تجد صور تفصيلية لكل عمل في المعرض. يمكنك أيضاً التواصل عبر واتساب لصور إضافية.' },
];
